const data = {
  sellOrders: [
    {
      _id: 1,
      creationDate: "YYYY-MM-DD",
      orderInfo: {
        externalOrderNumber: 1,
        sellerStore: "The better store",
        buyerName: "Pepe",
        buyerPhone: "333445566",
        buyerEmail: "mail@mail.com",
      },
      shippingInfo: {
        address: "Calle 1 #2-34",
        city: "Bogota",
        region: "Cundinamarca",
        country: "Colombia",
      },
      shippingMethod: "Express",
      promiseDates: {
        pack_promise_min: 1,
        pack_promise_max: 1,
        ship_promise_min: 1,
        ship_promise_min: 1,
        delivery_promise_min: 1,
        delivery_promise_max: 1,
        ready_pickup_promise_min: 1,
        ready_pickup_promise_max: 1,
      },
      items: [
        {
          productName: "name",
          productQuantity: 4,
          productWeight: 45,
        },
      ],
    },
    {
      _id: 2,
      creationDate: "YYYY-MM-DD",
      orderInfo: {
        externalOrderNumber: 1,
        sellerStore: "The better store",
        buyerName: "Pepe",
        buyerPhone: "333445566",
        buyerEmail: "mail@mail.com",
      },
      shippingInfo: {
        address: "Calle 1 #2-34",
        city: "Bogota",
        region: "Cundinamarca",
        country: "Colombia",
      },
      shippingMethod: "Express",
      promiseDates: {
        pack_promise_min: 1,
        pack_promise_max: 1,
        ship_promise_min: 1,
        ship_promise_min: 1,
        delivery_promise_min: 1,
        delivery_promise_max: 1,
        ready_pickup_promise_min: 1,
        ready_pickup_promise_max: 1,
      },
      items: [
        {
          productName: "name",
          productQuantity: 4,
          productWeight: 45,
        },
      ],
    },
    {
      _id: 3,
      creationDate: "YYYY-MM-DD",
      orderInfo: {
        externalOrderNumber: 1,
        sellerStore: "The better store",
        buyerName: "Pepe",
        buyerPhone: "333445566",
        buyerEmail: "mail@mail.com",
      },
      shippingInfo: {
        address: "Calle 1 #2-34",
        city: "Bogota",
        region: "Cundinamarca",
        country: "Colombia",
      },
      shippingMethod: "Express",
      promiseDates: {
        pack_promise_min: 1,
        pack_promise_max: 1,
        ship_promise_min: 1,
        ship_promise_min: 1,
        delivery_promise_min: 1,
        delivery_promise_max: 1,
        ready_pickup_promise_min: 1,
        ready_pickup_promise_max: 1,
      },
      items: [
        {
          productName: "name",
          productQuantity: 4,
          productWeight: 45,
        },
      ],
    },
    {
      _id: 4,
      creationDate: "YYYY-MM-DD",
      orderInfo: {
        externalOrderNumber: 1,
        sellerStore: "The better store",
        buyerName: "Pepe",
        buyerPhone: "333445566",
        buyerEmail: "mail@mail.com",
      },
      shippingInfo: {
        address: "Calle 1 #2-34",
        city: "Bogota",
        region: "Cundinamarca",
        country: "Colombia",
      },
      shippingMethod: "Express",
      promiseDates: {
        pack_promise_min: 1,
        pack_promise_max: 1,
        ship_promise_min: 1,
        ship_promise_min: 1,
        delivery_promise_min: 1,
        delivery_promise_max: 1,
        ready_pickup_promise_min: 1,
        ready_pickup_promise_max: 1,
      },
      items: [
        {
          productName: "name",
          productQuantity: 4,
          productWeight: 45,
        },
      ],
    },
    {
      _id: 5,
      creationDate: "YYYY-MM-DD",
      orderInfo: {
        externalOrderNumber: 1,
        sellerStore: "The better store",
        buyerName: "Pepe",
        buyerPhone: "333445566",
        buyerEmail: "mail@mail.com",
      },
      shippingInfo: {
        address: "Calle 1 #2-34",
        city: "Bogota",
        region: "Cundinamarca",
        country: "Colombia",
      },
      shippingMethod: "Express",
      promiseDates: {
        pack_promise_min: 1,
        pack_promise_max: 1,
        ship_promise_min: 1,
        ship_promise_min: 1,
        delivery_promise_min: 1,
        delivery_promise_max: 1,
        ready_pickup_promise_min: 1,
        ready_pickup_promise_max: 1,
      },
      items: [
        {
          productName: "name",
          productQuantity: 4,
          productWeight: 45,
        },
      ],
    },
  ],
};
export default data;
